[project]
name = 'photomarket'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.photo-token]
path = 'contracts/photo-token.clar'
clarity_version = 2
epoch = 2.5

[contracts.phototoken]
path = 'contracts/phototoken.clar'
clarity_version = 2
epoch = 2.5

[contracts.photoversev1]
path = 'contracts/photoversev1.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
